CREATE TABLE GROCERY_ITEMS(
GROCERY_ITEM varchar2(255) NOT NULL,
ITEM_TYPE VARCHAR2 (255) NOT NULL,
ID int NOT NULL,
CONSTRAINT ITEM_ID PRIMARY KEY (ID, GROCERY_ITEM)
);

CREATE TABLE GROCERY_LIST(
FIRST_NAME VARCHAR2(255) NOT NULL,
LAST_NAME VARCHAR2(255) NOT NULL,
ID INT NOT NULL,
CONSTRAINT LIST_ID PRIMARY KEY (ID, LAST_NAME)
)

COMMIT;